### ISSUE TITLE
How to ban users

### ISSUE THREAD

**Issue by Alpha119** [Code-X-Mania/filestreambot#10]
Bro plz tell how to ban or kick users to not send files & Don't making to spam bot

**Comment by Code-X-Mania** [comment]
ban in updates channel

**Comment by Alpha119** [comment]
How to ban bro it will Ban The Bot

**Comment by Alpha119** [comment]
I not used updates Channel

**Comment by Code-X-Mania** [comment]
No other way then sorry

**Comment by Alpha119** [comment]
Bro Can I Now Integrate Update Channel & Ban User

**Comment by Code-X-Mania** [comment]
Why not

**Comment by Alpha119** [comment]
Bro I Have A Doubt How To Broadcast Message Without Showing Forwarded From Message

**Comment by adarshg0el** [comment]
Al doubts on telegram @codexmaniachat  only issues to be posted here
