### ISSUE TITLE
Buffering 

### ISSUE THREAD

**Issue by zoredeaxx** [Code-X-Mania/filestreambot#4]
1. Even though the direct link download works well, however the video streaming is not very smooth especially while forwarding and reversing the stream resulting in considerable buffering time each time.
2. Please look into the issue if it can be improved...

**Comment by Code-X-Mania** [comment]
The issue is that when  2 many people request a file or if you using a free service the speed decreases so fkr now can't do anything also it buffers because it collects file from telegram and telegram give a low speed sometimes
