### ISSUE TITLE
features

### ISSUE THREAD

**Issue by rajeshsaini2115** [Code-X-Mania/filestreambot#6]
add photo support

**Comment by Code-X-Mania** [comment]
meaning?

**Comment by rajeshsaini2115** [comment]
mean when photo send it give download link
because I have 50+mb photo


and admin command not working

i tried check status and broadcast command

**Comment by adarshg0el** [comment]
@codexmaniachat telegram

**Comment by adarshg0el** [comment]
all your issues there only bugs and code problems here

**Comment by Code-X-Mania** [comment]
NOW REFORK ADDED THAT FEATURE
